services:
  - type: web
    name: medxbid-image-search
    env: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k sync --timeout 300 app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
